FROM node:alpine
WORKDIR "/app"
# Add environment variable to handle OpenSSL issue
ENV NODE_OPTIONS=--openssl-legacy-provider
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]