name: Multi-Container Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Optional: You can check Docker version and info
    steps:
      - name: Check Docker version
        run: docker --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t anshultaklikar/multicontainer-docker -f ./client/Dockerfile.dev ./client

      - name: Run tests inside Docker container
        run: docker run -e CI=true anshultaklikar/multicontainer-docker npm run test -- --coverage

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Login Docker
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker images
        run: |
          docker build -t anshultaklikar/multi-client:latest ./client
          docker build -t anshultaklikar/multi-nginx:latest ./nginx
          docker build -t anshultaklikar/multi-server:latest ./server
          docker build -t anshultaklikar/multi-worker:latest ./worker
      
      - name: Push to Docker hub
        run: |
          docker push anshultaklikar/multi-client:latest
          docker push anshultaklikar/multi-nginx:latest
          docker push anshultaklikar/multi-server:latest
          docker push anshultaklikar/multi-worker:latest

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
      
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v21
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: MyApplicationName
      #     environment_name: MyApplication-Environment
      #     version_label: ${{ github.sha }}
      #     existing_bucket_name: MyBucketName
      #     region: us-west-2
      #     deployment_package: deploy.zip